# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python CI

on:
  pull_request:
    branches: [ master, develop ]

  # Manually running a workflow
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        python_version: ['3.x']
        os: [ubuntu-latest, macOS-latest]

    name: Test with Python ${{ matrix.python_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}

    - name: Setup env
      env:
        TEST_IMAP_HOST: ${{ secrets.TEST_IMAP_HOST }}
        TEST_IMAP_PASSWORD: ${{ secrets.TEST_IMAP_PASSWORD }}
        TEST_IMAP_USERNAME: ${{ secrets.TEST_IMAP_USERNAME }}
      run: |
        echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV
        printenv > $(pwd)/.env

    - name: Setup requirements
      run: |
        python -m pip install --upgrade pip

        pip3 install -r requirements.txt
        pip3 install -r requirements.test.txt

    - name: Test lint
      continue-on-error: true
      run: |
        pylint imapinboxrules/

    - name: Test app
      run: |
        pytest \
          --cov imapinboxrules \
          --cov-branch \
          --cov-report term-missing \
          --cov-report xml

    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        flags: unittests
        name: github-action
        fail_ci_if_error: false
        verbose: true
